//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Point.com.Model
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    			public partial class B_InforConfigure:ModelBase
    {
        public Nullable<int> SysNo { get; set; }
        public Nullable<int> DataType { get; set; }
        public string ShowCrowd { get; set; }
        public string CoverPicUrl { get; set; }
        public string ShopName { get; set; }
        public string LogoPicUrl { get; set; }
        public Nullable<int> SetInvitationNum { get; set; }
        public Nullable<int> ReceiveType { get; set; }
        public Nullable<decimal> CouponMoney { get; set; }
        public string Title { get; set; }
        public string DescOne { get; set; }
        public string DescTwo { get; set; }
        public Nullable<decimal> MarketPrice { get; set; }
        public Nullable<decimal> PromotionPrice { get; set; }
        public Nullable<System.DateTime> RowCeateDate { get; set; }
        public Nullable<System.DateTime> ModifyTime { get; set; }
        public Nullable<bool> IsEnable { get; set; }
    }
}
