//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Point.com.Model
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    			public partial class Base_Region:ModelBase
    {
        public Nullable<int> RegionId { get; set; }
        public Nullable<int> ParentId { get; set; }
        public string RegionName { get; set; }
        public Nullable<int> RegionType { get; set; }
        public string ZipCode { get; set; }
        public string QuHao { get; set; }
        public string ShortSpell { get; set; }
        public Nullable<int> SortId { get; set; }
        public Nullable<bool> IsEnable { get; set; }
    }
}
