//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Point.com.Model
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    			public partial class Base_Deliver:ModelBase
    {
        public Nullable<int> IntDeliverID { get; set; }
        public string VchDeliverName { get; set; }
        public string VchDeliverDesc { get; set; }
        public Nullable<int> IntSort { get; set; }
        public Nullable<byte> IntIsCarriage { get; set; }
        public Nullable<byte> IntIsEnable { get; set; }
        public Nullable<int> IntAddUserID { get; set; }
        public Nullable<System.DateTime> DtAddDate { get; set; }
        public Nullable<int> IntModUserID { get; set; }
        public Nullable<System.DateTime> DtModDate { get; set; }
        public string Tb_code { get; set; }
        public Nullable<int> Tb_id { get; set; }
        public string Tb_name { get; set; }
        public string Tb_reg_mail_no { get; set; }
    }
}
