//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Point.com.Model
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    			public partial class base_t_member:ModelBase
    {
        public Nullable<int> MembNo { get; set; }
        public string UserCode { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> RegTime { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public string UpdateBy { get; set; }
        public string CardNO { get; set; }
        public Nullable<int> NoteFlag { get; set; }
        public Nullable<int> UserGroupId { get; set; }
        public Nullable<int> Policymaker { get; set; }
        public Nullable<int> ReferrerMembNo { get; set; }
        public Nullable<int> Province { get; set; }
        public Nullable<int> City { get; set; }
        public Nullable<int> District { get; set; }
        public Nullable<int> Scores { get; set; }
        public Nullable<int> Valid { get; set; }
        public string MobileTel { get; set; }
        public string Tel { get; set; }
        public string Email { get; set; }
        public Nullable<int> UserLevel { get; set; }
        public Nullable<int> AreaNo { get; set; }
        public Nullable<int> RegType { get; set; }
        public Nullable<int> ClusterId { get; set; }
        public Nullable<int> RegFrom { get; set; }
        public string Passward { get; set; }
        public string NickName { get; set; }
        public Nullable<byte> Sex { get; set; }
        public string Question { get; set; }
        public string Answer { get; set; }
        public string Qq { get; set; }
        public string Msn { get; set; }
        public Nullable<int> BeValidate { get; set; }
        public Nullable<int> OrderTimes { get; set; }
        public Nullable<int> IntUserType { get; set; }
        public byte[] Timestamp { get; set; }
        public Nullable<int> IsVfMobile { get; set; }
        public string LoginMobile { get; set; }
        public string VchRegMobEmail { get; set; }
        public string VchHeadImg { get; set; }
        public Nullable<int> SourceTypeSysNo { get; set; }
        public string ClientIp { get; set; }
        public string UserGuid { get; set; }
    }
}
