//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Point.com.Model
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    			public partial class Crm_User:ModelBase
    {
        public Nullable<int> SysNo { get; set; }
        public string Mobile { get; set; }
        public string MemPassWord { get; set; }
        public string MerchantName { get; set; }
        public string MerchantFullName { get; set; }
        public string MerchantAddress { get; set; }
        public Nullable<int> TotalPush { get; set; }
        public Nullable<int> TotalAttend { get; set; }
        public Nullable<int> TotalShare { get; set; }
        public Nullable<decimal> AccountBalance { get; set; }
        public Nullable<int> TotalNumber { get; set; }
        public Nullable<int> UserCount { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> RowCeateDate { get; set; }
        public Nullable<System.DateTime> ModifyTime { get; set; }
        public Nullable<bool> IsEnable { get; set; }
        public string BrandLogo { get; set; }
        public string MerchantMobile { get; set; }
        public string ShoppLink { get; set; }
        public string ContactPeople { get; set; }
        public string ComboPic { get; set; }
    }
}
