//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Point.com.Model
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    			public partial class T_InforConfigure:ModelBase
    {
        public Nullable<int> SysNo { get; set; }
        public Nullable<int> DataType { get; set; }
        public string StrInforType { get; set; }
        public string InforName { get; set; }
        public string InforRemark { get; set; }
        public string InforDesc { get; set; }
        public string LogoIcon { get; set; }
        public string HeadPic { get; set; }
        public string CoverPic { get; set; }
        public string ShopPic { get; set; }
        public string PushPic { get; set; }
        public string VideoUrl { get; set; }
        public Nullable<int> CateId { get; set; }
        public Nullable<int> ShopSysNo { get; set; }
        public Nullable<int> ShowMode { get; set; }
        public string InforSource { get; set; }
        public string LinkUrl { get; set; }
        public Nullable<int> IntSort { get; set; }
        public Nullable<int> IsShowIndex { get; set; }
        public Nullable<System.DateTime> SourceDateTime { get; set; }
        public Nullable<System.DateTime> RowCeateDate { get; set; }
        public Nullable<System.DateTime> ModifyTime { get; set; }
        public Nullable<bool> IsEnable { get; set; }
    }
}
