//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Point.com.Model
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    			public partial class T_Member:ModelBase
    {
        public Nullable<int> SysNo { get; set; }
        public string Mobile { get; set; }
        public string Portrait { get; set; }
        public string MemPassWord { get; set; }
        public string NickName { get; set; }
        public Nullable<int> Sex { get; set; }
        public Nullable<int> RegProvince { get; set; }
        public Nullable<int> RegCity { get; set; }
        public Nullable<int> RegArea { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public Nullable<int> InforType { get; set; }
        public Nullable<decimal> Account { get; set; }
        public Nullable<decimal> AccountWithdrawn { get; set; }
        public Nullable<decimal> Score { get; set; }
        public Nullable<decimal> ScoreWithdrawn { get; set; }
        public string OpenidWxOpen { get; set; }
        public Nullable<System.DateTime> LastLoginTime { get; set; }
        public Nullable<int> SourceTypeSysNo { get; set; }
        public string DeviceCode { get; set; }
        public string MobileModel { get; set; }
        public string ClientIp { get; set; }
        public Nullable<decimal> MinWithdrawals { get; set; }
        public Nullable<System.DateTime> RowCeateDate { get; set; }
        public Nullable<System.DateTime> ModifyTime { get; set; }
        public byte[] Timestamp { get; set; }
    }
}
