//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Point.com.Model
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    			public partial class T_SelfMediaArticle:ModelBase
    {
        public Nullable<int> SysNo { get; set; }
        public string StrInforType { get; set; }
        public Nullable<int> AuthorSysNo { get; set; }
        public string HeadPic { get; set; }
        public string Title { get; set; }
        public string Subtitle { get; set; }
        public string Content { get; set; }
        public Nullable<decimal> ReadScore { get; set; }
        public Nullable<bool> IsHot { get; set; }
        public Nullable<int> ShowMode { get; set; }
        public Nullable<int> IsShowIndex { get; set; }
        public Nullable<int> SortId { get; set; }
        public Nullable<System.DateTime> RowCeateDate { get; set; }
        public Nullable<System.DateTime> ModifyTime { get; set; }
        public Nullable<bool> IsEnable { get; set; }
    }
}
