#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18063
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Point.Pull
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="point")]
	public partial class PointDataDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void InsertTaobao_tbk_dg_item_coupon_get(Taobao_tbk_dg_item_coupon_get instance);
    partial void UpdateTaobao_tbk_dg_item_coupon_get(Taobao_tbk_dg_item_coupon_get instance);
    partial void DeleteTaobao_tbk_dg_item_coupon_get(Taobao_tbk_dg_item_coupon_get instance);
    #endregion
		
		public PointDataDataContext() : 
				base(global::Point.Pull.Properties.Settings.Default.pointConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public PointDataDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PointDataDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PointDataDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PointDataDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Taobao_tbk_dg_item_coupon_get> Taobao_tbk_dg_item_coupon_get
		{
			get
			{
				return this.GetTable<Taobao_tbk_dg_item_coupon_get>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Taobao_tbk_dg_item_coupon_get")]
	public partial class Taobao_tbk_dg_item_coupon_get : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _SysNo;
		
		private string _Shop_title;
		
		private System.Nullable<int> _User_type;
		
		private string _Zk_final_price;
		
		private string _Title;
		
		private string _Nick;
		
		private System.Nullable<long> _Seller_id;
		
		private System.Nullable<long> _Volume;
		
		private string _Pict_url;
		
		private string _Item_url;
		
		private System.Nullable<long> _Coupon_total_count;
		
		private string _Commission_rate;
		
		private string _Coupon_info;
		
		private System.Nullable<int> _Category;
		
		private System.Nullable<long> _Num_iid;
		
		private System.Nullable<long> _Coupon_remain_count;
		
		private string _Coupon_start_time;
		
		private string _Coupon_end_time;
		
		private string _Coupon_click_url;
		
		private string _Item_description;
		
		private string _Small_images;
		
		private System.DateTime _RowCreateTime;
		
		private bool _IsHandle;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSysNoChanging(int value);
    partial void OnSysNoChanged();
    partial void OnShop_titleChanging(string value);
    partial void OnShop_titleChanged();
    partial void OnUser_typeChanging(System.Nullable<int> value);
    partial void OnUser_typeChanged();
    partial void OnZk_final_priceChanging(string value);
    partial void OnZk_final_priceChanged();
    partial void OnTitleChanging(string value);
    partial void OnTitleChanged();
    partial void OnNickChanging(string value);
    partial void OnNickChanged();
    partial void OnSeller_idChanging(System.Nullable<long> value);
    partial void OnSeller_idChanged();
    partial void OnVolumeChanging(System.Nullable<long> value);
    partial void OnVolumeChanged();
    partial void OnPict_urlChanging(string value);
    partial void OnPict_urlChanged();
    partial void OnItem_urlChanging(string value);
    partial void OnItem_urlChanged();
    partial void OnCoupon_total_countChanging(System.Nullable<long> value);
    partial void OnCoupon_total_countChanged();
    partial void OnCommission_rateChanging(string value);
    partial void OnCommission_rateChanged();
    partial void OnCoupon_infoChanging(string value);
    partial void OnCoupon_infoChanged();
    partial void OnCategoryChanging(System.Nullable<int> value);
    partial void OnCategoryChanged();
    partial void OnNum_iidChanging(System.Nullable<long> value);
    partial void OnNum_iidChanged();
    partial void OnCoupon_remain_countChanging(System.Nullable<long> value);
    partial void OnCoupon_remain_countChanged();
    partial void OnCoupon_start_timeChanging(string value);
    partial void OnCoupon_start_timeChanged();
    partial void OnCoupon_end_timeChanging(string value);
    partial void OnCoupon_end_timeChanged();
    partial void OnCoupon_click_urlChanging(string value);
    partial void OnCoupon_click_urlChanged();
    partial void OnItem_descriptionChanging(string value);
    partial void OnItem_descriptionChanged();
    partial void OnSmall_imagesChanging(string value);
    partial void OnSmall_imagesChanged();
    partial void OnRowCreateTimeChanging(System.DateTime value);
    partial void OnRowCreateTimeChanged();
    partial void OnIsHandleChanging(bool value);
    partial void OnIsHandleChanged();
    #endregion
		
		public Taobao_tbk_dg_item_coupon_get()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SysNo", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int SysNo
		{
			get
			{
				return this._SysNo;
			}
			set
			{
				if ((this._SysNo != value))
				{
					this.OnSysNoChanging(value);
					this.SendPropertyChanging();
					this._SysNo = value;
					this.SendPropertyChanged("SysNo");
					this.OnSysNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Shop_title", DbType="NVarChar(256)")]
		public string Shop_title
		{
			get
			{
				return this._Shop_title;
			}
			set
			{
				if ((this._Shop_title != value))
				{
					this.OnShop_titleChanging(value);
					this.SendPropertyChanging();
					this._Shop_title = value;
					this.SendPropertyChanged("Shop_title");
					this.OnShop_titleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_type", DbType="Int")]
		public System.Nullable<int> User_type
		{
			get
			{
				return this._User_type;
			}
			set
			{
				if ((this._User_type != value))
				{
					this.OnUser_typeChanging(value);
					this.SendPropertyChanging();
					this._User_type = value;
					this.SendPropertyChanged("User_type");
					this.OnUser_typeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Zk_final_price", DbType="NVarChar(32)")]
		public string Zk_final_price
		{
			get
			{
				return this._Zk_final_price;
			}
			set
			{
				if ((this._Zk_final_price != value))
				{
					this.OnZk_final_priceChanging(value);
					this.SendPropertyChanging();
					this._Zk_final_price = value;
					this.SendPropertyChanged("Zk_final_price");
					this.OnZk_final_priceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="NVarChar(256)")]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this.OnTitleChanging(value);
					this.SendPropertyChanging();
					this._Title = value;
					this.SendPropertyChanged("Title");
					this.OnTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nick", DbType="NVarChar(64)")]
		public string Nick
		{
			get
			{
				return this._Nick;
			}
			set
			{
				if ((this._Nick != value))
				{
					this.OnNickChanging(value);
					this.SendPropertyChanging();
					this._Nick = value;
					this.SendPropertyChanged("Nick");
					this.OnNickChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Seller_id", DbType="BigInt")]
		public System.Nullable<long> Seller_id
		{
			get
			{
				return this._Seller_id;
			}
			set
			{
				if ((this._Seller_id != value))
				{
					this.OnSeller_idChanging(value);
					this.SendPropertyChanging();
					this._Seller_id = value;
					this.SendPropertyChanged("Seller_id");
					this.OnSeller_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Volume", DbType="BigInt")]
		public System.Nullable<long> Volume
		{
			get
			{
				return this._Volume;
			}
			set
			{
				if ((this._Volume != value))
				{
					this.OnVolumeChanging(value);
					this.SendPropertyChanging();
					this._Volume = value;
					this.SendPropertyChanged("Volume");
					this.OnVolumeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pict_url", DbType="VarChar(512)")]
		public string Pict_url
		{
			get
			{
				return this._Pict_url;
			}
			set
			{
				if ((this._Pict_url != value))
				{
					this.OnPict_urlChanging(value);
					this.SendPropertyChanging();
					this._Pict_url = value;
					this.SendPropertyChanged("Pict_url");
					this.OnPict_urlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Item_url", DbType="VarChar(512)")]
		public string Item_url
		{
			get
			{
				return this._Item_url;
			}
			set
			{
				if ((this._Item_url != value))
				{
					this.OnItem_urlChanging(value);
					this.SendPropertyChanging();
					this._Item_url = value;
					this.SendPropertyChanged("Item_url");
					this.OnItem_urlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Coupon_total_count", DbType="BigInt")]
		public System.Nullable<long> Coupon_total_count
		{
			get
			{
				return this._Coupon_total_count;
			}
			set
			{
				if ((this._Coupon_total_count != value))
				{
					this.OnCoupon_total_countChanging(value);
					this.SendPropertyChanging();
					this._Coupon_total_count = value;
					this.SendPropertyChanged("Coupon_total_count");
					this.OnCoupon_total_countChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Commission_rate", DbType="VarChar(32)")]
		public string Commission_rate
		{
			get
			{
				return this._Commission_rate;
			}
			set
			{
				if ((this._Commission_rate != value))
				{
					this.OnCommission_rateChanging(value);
					this.SendPropertyChanging();
					this._Commission_rate = value;
					this.SendPropertyChanged("Commission_rate");
					this.OnCommission_rateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Coupon_info", DbType="VarChar(32)")]
		public string Coupon_info
		{
			get
			{
				return this._Coupon_info;
			}
			set
			{
				if ((this._Coupon_info != value))
				{
					this.OnCoupon_infoChanging(value);
					this.SendPropertyChanging();
					this._Coupon_info = value;
					this.SendPropertyChanged("Coupon_info");
					this.OnCoupon_infoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Category", DbType="Int")]
		public System.Nullable<int> Category
		{
			get
			{
				return this._Category;
			}
			set
			{
				if ((this._Category != value))
				{
					this.OnCategoryChanging(value);
					this.SendPropertyChanging();
					this._Category = value;
					this.SendPropertyChanged("Category");
					this.OnCategoryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Num_iid", DbType="BigInt")]
		public System.Nullable<long> Num_iid
		{
			get
			{
				return this._Num_iid;
			}
			set
			{
				if ((this._Num_iid != value))
				{
					this.OnNum_iidChanging(value);
					this.SendPropertyChanging();
					this._Num_iid = value;
					this.SendPropertyChanged("Num_iid");
					this.OnNum_iidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Coupon_remain_count", DbType="BigInt")]
		public System.Nullable<long> Coupon_remain_count
		{
			get
			{
				return this._Coupon_remain_count;
			}
			set
			{
				if ((this._Coupon_remain_count != value))
				{
					this.OnCoupon_remain_countChanging(value);
					this.SendPropertyChanging();
					this._Coupon_remain_count = value;
					this.SendPropertyChanged("Coupon_remain_count");
					this.OnCoupon_remain_countChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Coupon_start_time", DbType="VarChar(128)")]
		public string Coupon_start_time
		{
			get
			{
				return this._Coupon_start_time;
			}
			set
			{
				if ((this._Coupon_start_time != value))
				{
					this.OnCoupon_start_timeChanging(value);
					this.SendPropertyChanging();
					this._Coupon_start_time = value;
					this.SendPropertyChanged("Coupon_start_time");
					this.OnCoupon_start_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Coupon_end_time", DbType="VarChar(128)")]
		public string Coupon_end_time
		{
			get
			{
				return this._Coupon_end_time;
			}
			set
			{
				if ((this._Coupon_end_time != value))
				{
					this.OnCoupon_end_timeChanging(value);
					this.SendPropertyChanging();
					this._Coupon_end_time = value;
					this.SendPropertyChanged("Coupon_end_time");
					this.OnCoupon_end_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Coupon_click_url", DbType="VarChar(512)")]
		public string Coupon_click_url
		{
			get
			{
				return this._Coupon_click_url;
			}
			set
			{
				if ((this._Coupon_click_url != value))
				{
					this.OnCoupon_click_urlChanging(value);
					this.SendPropertyChanging();
					this._Coupon_click_url = value;
					this.SendPropertyChanged("Coupon_click_url");
					this.OnCoupon_click_urlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Item_description", DbType="NVarChar(256)")]
		public string Item_description
		{
			get
			{
				return this._Item_description;
			}
			set
			{
				if ((this._Item_description != value))
				{
					this.OnItem_descriptionChanging(value);
					this.SendPropertyChanging();
					this._Item_description = value;
					this.SendPropertyChanged("Item_description");
					this.OnItem_descriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Small_images", DbType="NVarChar(MAX)")]
		public string Small_images
		{
			get
			{
				return this._Small_images;
			}
			set
			{
				if ((this._Small_images != value))
				{
					this.OnSmall_imagesChanging(value);
					this.SendPropertyChanging();
					this._Small_images = value;
					this.SendPropertyChanged("Small_images");
					this.OnSmall_imagesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RowCreateTime", DbType="DateTime NOT NULL")]
		public System.DateTime RowCreateTime
		{
			get
			{
				return this._RowCreateTime;
			}
			set
			{
				if ((this._RowCreateTime != value))
				{
					this.OnRowCreateTimeChanging(value);
					this.SendPropertyChanging();
					this._RowCreateTime = value;
					this.SendPropertyChanged("RowCreateTime");
					this.OnRowCreateTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsHandle", DbType="Bit NOT NULL")]
		public bool IsHandle
		{
			get
			{
				return this._IsHandle;
			}
			set
			{
				if ((this._IsHandle != value))
				{
					this.OnIsHandleChanging(value);
					this.SendPropertyChanging();
					this._IsHandle = value;
					this.SendPropertyChanged("IsHandle");
					this.OnIsHandleChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
